### ISSUE TITLE
"em" functions should be added

### ISSUE THREAD

**Issue by ZeeCoder** [ZeeCoder/generator-z-frontend#22]
And documentation about them, too.

```scss
$em-base: 10;

@function em-base($new-base) {
    $em-base: $new-base;

    @return ($em-base * 1px);
}

@function em($px-value, $custom-base: null) {
    @if $custom-base == null {
        $custom-base: $em-base;
    }

    @return ($px-value / $custom-base * 1em);
}

```
